//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingEasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerQuestion()
        {
            this.UserAnswer = new HashSet<UserAnswer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AnswerId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<bool> IsRight { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual Questions Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnswer> UserAnswer { get; set; }
    }
}
