//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingEasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsTicket
    {
        public int Id { get; set; }
        public Nullable<int> TicketId { get; set; }
        public Nullable<int> QuestionsId { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
