//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingEasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TypeClassId { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeClass TypeClass { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
