//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrivingEasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public int Id { get; set; }
        public Nullable<int> AnswerQuestionId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual AnswerQuestion AnswerQuestion { get; set; }
        public virtual User User { get; set; }
    }
}
